/**
 * Placeholder quote data for development when the database is unavailable
 * or returns no results. Used by feed queries and by Home/Explore clients.
 */

import type { QuoteData } from "@/types/quote";

const now = new Date();
const dayAgo = new Date(now.getTime() - 86400000);
const twoDaysAgo = new Date(now.getTime() - 172800000);

export const PLACEHOLDER_QUOTES_FEED: QuoteData[] = [
  {
    id: "ph-1",
    text: "The best way to predict the future is to design it.",
    attribution: "Buckminster Fuller",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Switzer",
    fontSecondary: "Inter",
    colorPalette: null,
    mood: "bold",
    cardImageUrl: null,
    publishedAt: now.toISOString(),
    submitter: { id: "s1", name: "Dianna", profilePhoto: null, image: null },
  },
  {
    id: "ph-2",
    text: "White space is to be regarded as an active element, not a passive background.",
    attribution: "Jan Tschichold",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Cormorant Garamond",
    fontSecondary: "Source Sans Pro",
    colorPalette: null,
    mood: "serene",
    cardImageUrl: null,
    publishedAt: dayAgo.toISOString(),
    submitter: { id: "s2", name: "Robert", profilePhoto: null, image: null },
  },
  {
    id: "ph-3",
    text: "Good design is as little design as possible.",
    attribution: "Dieter Rams",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Space Grotesk",
    fontSecondary: "DM Sans",
    colorPalette: null,
    mood: "minimal",
    cardImageUrl: null,
    publishedAt: twoDaysAgo.toISOString(),
    submitter: null,
  },
  {
    id: "ph-4",
    text: "Simplicity is the ultimate sophistication.",
    attribution: "Leonardo da Vinci",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Inter",
    fontSecondary: "Inter",
    colorPalette: null,
    mood: "elegant",
    cardImageUrl: null,
    publishedAt: new Date("2024-04-25T11:00:00Z").toISOString(),
    submitter: { id: "s3", name: "Micah", profilePhoto: null, image: null },
  },
  {
    id: "ph-5",
    text: "Design is intelligence made visible.",
    attribution: "Alina Wheeler",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Space Grotesk",
    fontSecondary: "Switzer",
    colorPalette: null,
    mood: "modern",
    cardImageUrl: null,
    publishedAt: new Date("2024-03-10T09:30:00Z").toISOString(),
    submitter: { id: "s4", name: "Arjun", profilePhoto: null, image: null },
  },
  {
    id: "ph-6",
    text: "Styles come and go. Good design is a language, not a style.",
    attribution: "Massimo Vignelli",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Cormorant Garamond",
    fontSecondary: "Space Grotesk",
    colorPalette: null,
    mood: "timeless",
    cardImageUrl: null,
    publishedAt: new Date("2023-12-12T16:45:00Z").toISOString(),
    submitter: null,
  },
  {
    id: "ph-7",
    text: "Don’t design for brands. Design for people interacting with brands.",
    attribution: "Abhijit Deshpande",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Switzer",
    fontSecondary: "DM Sans",
    colorPalette: null,
    mood: "bold",
    cardImageUrl: null,
    publishedAt: new Date("2023-09-18T06:21:00Z").toISOString(),
    submitter: { id: "s5", name: "Jenna", profilePhoto: null, image: null },
  },
  {
    id: "ph-8",
    text: "Design adds value faster than it adds costs.",
    attribution: "Joel Spolsky",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "DM Sans",
    fontSecondary: "Cormorant Garamond",
    colorPalette: null,
    mood: "pragmatic",
    cardImageUrl: null,
    publishedAt: new Date("2023-05-30T02:10:45Z").toISOString(),
    submitter: { id: "s6", name: "Bella", profilePhoto: null, image: null },
  },
  {
    id: "ph-9",
    text: "Design is not just what it looks like and feels like. Design is how it works.",
    attribution: "Steve Jobs",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Inter",
    fontSecondary: "DM Sans",
    colorPalette: null,
    mood: "functional",
    cardImageUrl: null,
    publishedAt: new Date("2023-02-14T15:00:00Z").toISOString(),
    submitter: { id: "s7", name: "Ken", profilePhoto: null, image: null },
  },
  {
    id: "ph-10",
    text: "A user interface is like a joke. If you have to explain it, it’s not that good.",
    attribution: "Martin LeBlanc",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Space Grotesk",
    fontSecondary: "Switzer",
    colorPalette: null,
    mood: "humorous",
    cardImageUrl: null,
    publishedAt: new Date("2022-11-08T12:00:00Z").toISOString(),
    submitter: null,
  },
  {
    id: "ph-11",
    text: "The details are not the details. They make the design.",
    attribution: "Charles Eames",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Cormorant Garamond",
    fontSecondary: "Space Grotesk",
    colorPalette: null,
    mood: "thoughtful",
    cardImageUrl: null,
    publishedAt: new Date("2022-08-18T21:15:00Z").toISOString(),
    submitter: { id: "s8", name: "Liam", profilePhoto: null, image: null },
  },
  {
    id: "ph-12",
    text: "Design everything on the assumption that people are not heartless or stupid but marvelously capable, given the chance.",
    attribution: "John Chris Jones",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "DM Sans",
    fontSecondary: "Switzer",
    colorPalette: null,
    mood: "inspirational",
    cardImageUrl: null,
    publishedAt: new Date("2022-02-28T10:20:00Z").toISOString(),
    submitter: { id: "s9", name: "Sophie", profilePhoto: null, image: null },
  },
  {
    id: "ph-13",
    text: "Every great design begins with an even better story.",
    attribution: "Lorinda Mamo",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Switzer",
    fontSecondary: "Cormorant Garamond",
    colorPalette: null,
    mood: "creative",
    cardImageUrl: null,
    publishedAt: new Date("2021-12-13T08:00:00Z").toISOString(),
    submitter: { id: "s10", name: "Leo", profilePhoto: null, image: null },
  },
  {
    id: "ph-14",
    text: "Whitespace is like air: it is necessary for design to breathe.",
    attribution: "Wojciech Zieliński",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Inter",
    fontSecondary: "DM Sans",
    colorPalette: null,
    mood: "serene",
    cardImageUrl: null,
    publishedAt: new Date("2021-09-03T22:40:00Z").toISOString(),
    submitter: null,
  },
  {
    id: "ph-15",
    text: "Design creates culture. Culture shapes values. Values determine the future.",
    attribution: "Robert L. Peters",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Cormorant Garamond",
    fontSecondary: "Space Grotesk",
    colorPalette: null,
    mood: "philosophical",
    cardImageUrl: null,
    publishedAt: new Date("2021-05-16T18:30:27Z").toISOString(),
    submitter: { id: "s11", name: "Aiyana", profilePhoto: null, image: null },
  },
  {
    id: "ph-16",
    text: "It’s through mistakes that you actually can grow. You have to get bad in order to get good.",
    attribution: "Paula Scher",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Space Grotesk",
    fontSecondary: "Inter",
    colorPalette: null,
    mood: "encouraging",
    cardImageUrl: null,
    publishedAt: new Date("2020-12-31T23:55:00Z").toISOString(),
    submitter: null,
  },
  {
    id: "ph-17",
    text: "Just because something looks good doesn’t mean it’s useful. And just because something is useful doesn’t mean it can’t be beautiful.",
    attribution: "Joshua Brewer",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Switzer",
    fontSecondary: "DM Sans",
    colorPalette: null,
    mood: "balanced",
    cardImageUrl: null,
    publishedAt: new Date("2020-08-15T04:20:23Z").toISOString(),
    submitter: { id: "s12", name: "Min", profilePhoto: null, image: null },
  },
  {
    id: "ph-18",
    text: "Get rid of everything that is not essential to making a point.",
    attribution: "Christoph Niemann",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "DM Sans",
    fontSecondary: "Cormorant Garamond",
    colorPalette: null,
    mood: "minimal",
    cardImageUrl: null,
    publishedAt: new Date("2020-03-20T13:10:00Z").toISOString(),
    submitter: { id: "s13", name: "Sara", profilePhoto: null, image: null },
  },
  {
    id: "ph-19",
    text: "Design must reflect the practical and aesthetic in business but above all... good design must primarily serve people.",
    attribution: "Thomas J. Watson",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Cormorant Garamond",
    fontSecondary: "Inter",
    colorPalette: null,
    mood: "purposeful",
    cardImageUrl: null,
    publishedAt: new Date("2019-10-09T17:40:00Z").toISOString(),
    submitter: null,
  },
  {
    id: "ph-20",
    text: "People ignore design that ignores people.",
    attribution: "Frank Chimero",
    socialHandles: [],
    authorPhoto: null,
    backgroundId: null,
    backgroundUrl: null,
    fontPrimary: "Switzer",
    fontSecondary: "Space Grotesk",
    colorPalette: null,
    mood: "people-centric",
    cardImageUrl: null,
    publishedAt: new Date("2019-01-03T07:15:00Z").toISOString(),
    submitter: { id: "s14", name: "Raj", profilePhoto: null, image: null },
  },
];

/**
 * Use placeholder quotes in development when DB is not available.
 * Set USE_PLACEHOLDER_QUOTES=true to force placeholders in any environment.
 */
export function usePlaceholderQuotesInDev(): boolean {
  if (process.env.USE_PLACEHOLDER_QUOTES === "true") return true;
  return process.env.NODE_ENV === "development";
}
